security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
              pattern:            /admin(.*)
              anonymous:    true
              form_login:
                  provider:       fos_userbundle
                  login_path:     /admin/login
                  check_path:     /admin/login_check
                  default_target_path: /admin
              logout:
                  path:           /admin/logout
                  target:         /admin/login


    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }