<?php

namespace AppBundle\Entity\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function findAllNames()
    {
        $names =  $this->getEntityManager()
            ->createQuery("SELECT c.name as name
                           FROM AppBundle:Category c
                           ")
            ->getResult();

        return array_map(function($item){ return $item['name']; }, $names);
    }
}
