<?php

namespace AppBundle\Entity\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllForPagination()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT i.name
                           FROM AppBundle:Item i
                           ");
    }


    /**
     * @param $name
     * @return \Doctrine\ORM\Query
     */
    public function findAllByCategoriesForPagination($name)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT i
                           FROM AppBundle:Item i
                           JOIN i.categories c
                           WHERE c.name = :name
                           ")
            ->setParameter('name', $name);
    }
}
